mysql:
  image: mysql:5.6
  ports:
    - "18100:3306"
  container_name: flagr-mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=flagr
    - MYSQL_USER=root
  volumes:
    - ./_data/mysql:/var/lib/mysql

zookeeper:
  image: confluentinc/cp-zookeeper
  container_name: flagr-zookeeper
  environment:
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 2000
  ports:
    - "2181:2181"
  extra_hosts:
    - "moby:127.0.0.1"

kafka:
  image: confluentinc/cp-kafka
  container_name: flagr-kafka
  links:
    - zookeeper
  environment:
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    KAFKA_BROKER_ID: 1
  ports:
    - "9092:9092"
  extra_hosts:
    - "moby:127.0.0.1"
  volumes:
    - ./_data/kafka:/var/lib/kafka

kafka-manager:
  image: sheepkiller/kafka-manager
  container_name: flagr-kafka-manager
  ports:
    - "9000:9000"
  links:
    - zookeeper
    - kafka
  environment:
    ZK_HOSTS: "zookeeper:2181"
  extra_hosts:
    - "moby:127.0.0.1"
