# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  unit_test:
    docker:
      - image: golang:1.14
    working_directory: /go/src/github.com/checkr/flagr
    steps:
      - checkout
      - run: make deps
      - run: make ci
      - run: bash <(curl -s https://codecov.io/bash)

  ui_lint:
    docker:
      - image: node:10
    working_directory: /go/src/github.com/checkr/flagr
    steps:
      - checkout
      - run: cd browser/flagr-ui && npm install
      - run: cd browser/flagr-ui && npm run lint

  integration_test:
    docker:
      - image: checkr/docker-docker-compose
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
          docker_layer_caching: true
      - run: cd integration_tests && make build-image
      - run: cd integration_tests && make down
      - run: cd integration_tests && make up
      - run: cd integration_tests && make test

workflows:
  version: 2
  test:
    jobs:
      - unit_test
      - ui_lint
      - integration_test
